### ISSUE TITLE
Any chance you could update this for godot 4 . 

### ISSUE THREAD

**Issue by DigitalRecline** [GDQuest/godot-2d-jrpg-combat#3]
Hi 
Wondering if you can update for Godot 4.3. looks like there is a lot of promising things for me to learn from this.

regards

**Comment by NathanLovato** [comment]
This is being slowly remade in a much more comprehensive Godot demo, Godot Open RPG here: https://github.com/gdquest-demos/godot-open-rpg

This repository itself will not get an update, but Godot Open RPG has been shaping up to cover more than this. It's mostly missing the UI and animations in the combat system now.
